name: 'airstats'
version: '1.0.0'
config-version: 2

profile: 'airstats'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airstats:
    bronze:
      +materialized: ephemeral
    silver:
      +materialized: table

tests:
  airstats:
    +store_failures: true
    +schema: test_failures
